package com.focusclinic.app.presentation

object Strings {
    // App
    const val APP_NAME = "Focus Clinic"

    // Bottom Navigation
    const val NAV_FOCUS = "Focus"
    const val NAV_CLINIC = "Clinic"
    const val NAV_SHOP = "Shop"
    const val NAV_STATS = "Stats"

    // Focus Screen
    const val FOCUS_TITLE = "Focus Session"
    const val FOCUS_SELECT_DURATION = "Select Duration"
    const val FOCUS_START = "Start Focus"
    const val FOCUS_CANCEL = "Cancel"
    const val FOCUS_MINUTES_SUFFIX = "min"
    const val FOCUS_TIME_REMAINING = "Time Remaining"
    const val FOCUS_PATIENT_WAITING = "Your patient is waiting..."
    const val FOCUS_PATIENT_TREATING = "Treating patient..."
    const val FOCUS_PATIENT_HAPPY = "Patient treated successfully!"
    const val FOCUS_PATIENT_ANGRY = "Patient left angrily!"
    const val FOCUS_SESSION_CANCELLED = "Session cancelled"
    const val FOCUS_COMPLETED_TITLE = "Session Complete!"
    const val FOCUS_INTERRUPTED_TITLE = "Session Interrupted"
    const val FOCUS_EARNED_XP = "XP Earned"
    const val FOCUS_EARNED_COINS = "Coins Earned"
    const val FOCUS_CONTINUE = "Continue"
    const val FOCUS_BALANCE = "Balance"

    // Shop Screen
    const val SHOP_TAB_VIRTUAL = "Clinic Shop"
    const val SHOP_TAB_REWARDS = "My Rewards"
    const val SHOP_OWNED = "Owned"
    const val SHOP_BUY = "Buy"
    const val SHOP_REDEEM = "Redeem"
    const val SHOP_CREATE_REWARD = "Create Reward"
    const val SHOP_REWARD_TITLE = "Reward title"
    const val SHOP_REWARD_COST = "Cost (coins)"
    const val SHOP_SAVE = "Save"
    const val SHOP_CANCEL = "Cancel"
    const val SHOP_NO_REWARDS = "No rewards yet. Create one!"
    const val SHOP_XP_BONUS = "XP"
    const val SHOP_COIN_BONUS = "Coin"
    const val SHOP_DECORATION = "Decor"
    const val SHOP_PURCHASED = "Purchased!"
    const val SHOP_REDEEMED = "Redeemed!"
    const val SHOP_DELETE_CONFIRM = "Delete this reward?"
    const val SHOP_YES = "Yes"
    const val SHOP_NO = "No"

    // Clinic Screen
    const val CLINIC_TITLE = "My Clinic"
    const val CLINIC_LEVEL = "Level"
    const val CLINIC_XP_PROGRESS = "XP Progress"
    const val CLINIC_XP_TO_NEXT = "XP to next level"
    const val CLINIC_MAX_LEVEL = "Max Level Reached!"
    const val CLINIC_MULTIPLIERS = "Active Multipliers"
    const val CLINIC_XP_MULTIPLIER = "XP Multiplier"
    const val CLINIC_COIN_MULTIPLIER = "Coin Multiplier"
    const val CLINIC_EQUIPMENT = "Equipment"
    const val CLINIC_DECORATIONS = "Decorations"
    const val CLINIC_EMPTY_ROOM = "Your clinic is empty. Visit the shop!"
    const val CLINIC_NO_EQUIPMENT = "No equipment yet"
    const val CLINIC_NO_DECORATIONS = "No decorations yet"

    // Stats Screen
    const val STATS_TITLE = "Statistics"
    const val STATS_TOTAL_SESSIONS = "Sessions"
    const val STATS_COMPLETED = "Completed"
    const val STATS_TOTAL_FOCUS = "Focus Time"
    const val STATS_TOTAL_XP = "Total XP"
    const val STATS_TOTAL_COINS = "Total Coins"
    const val STATS_SESSION_HISTORY = "Session History"
    const val STATS_NO_SESSIONS = "No sessions yet. Start focusing!"
    const val STATS_HOURS_SUFFIX = "h"
    const val STATS_MINUTES_SUFFIX = "m"
    const val STATS_STATUS_COMPLETED = "Completed"
    const val STATS_STATUS_INTERRUPTED = "Interrupted"
    const val STATS_STATUS_CANCELLED = "Cancelled"

    // Goals Screen
    const val GOALS_TITLE = "Goals"
    const val GOALS_ADD = "Add goal"
    const val GOALS_EMPTY = "No goals yet. Create one!"
    const val GOALS_EMPTY_ICON = "\uD83C\uDFAF"
    const val GOALS_COMPLETE = "Complete"
    const val GOALS_EDIT = "Edit"
    const val GOALS_DELETE = "Delete"
    const val GOALS_COIN_REWARD = "Coins"
    const val GOALS_XP_REWARD = "XP"
    const val GOALS_CREATE_TITLE = "Create Goal"
    const val GOALS_EDIT_TITLE = "Edit Goal"
    const val GOALS_FIELD_TITLE = "Goal title"
    const val GOALS_FIELD_DESCRIPTION = "Description (optional)"
    const val GOALS_FIELD_COINS = "Coin reward"
    const val GOALS_FIELD_XP = "XP reward"
    const val GOALS_SAVE = "Save"
    const val GOALS_CANCEL = "Cancel"
    const val GOALS_COMPLETED_SUCCESS = "Goal completed!"

    // Content Descriptions
    const val CD_TIMER = "Session timer"
    const val CD_PATIENT = "Patient status"
    const val CD_COIN_ICON = "Coins"
    const val CD_XP_ICON = "Experience points"
}
